baseURL = 'https://mathieuhendey.com/'
canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = 'UA-28625544-1'
summaryLength = 2
title = 'Mathieu Hendey'
weight = 1

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[taxonomies]
category = 'categories'
tag = 'tags'

[permalinks]
page = '/:slug/'
posts = '/:year/:month/:slug/'

[params]
languageCode = 'en-GB'
languageName = 'English'
colortheme = 'light'
description = '''I am a software developer currently working on SIMs and IOT for Arm. Before that I spent a few years working on various UK government projects managed by GDS.'''
rss = true
showallpostsonhomepage = false
ShowProjectsList = false
postsonhomepage = 10
author = 'Mathieu Hendey'
github = 'https://github.com/mathieuhendey'
og_image = '/img/og_image.png'
sitename = 'Mathieu Hendey'
twitter = '@mathieu_hendey'
mainSections = ['all posts']
logo = '/img/logo.png'

[[params.social]]
link = 'https://github.com/mathieuhendey'
name = 'github'

[[params.social]]
link = 'https://news.ycombinator.com/user?id=mathieuh'
name = 'hacker-news'

[[params.social]]
link = 'm@mathieuhendey.com'
name = 'email'

[[params.social]]
link = 'https://twitter.com/mathieu_hendey'
name = 'twitter'

[[params.social]]
link = 'https://www.linkedin.com/in/mathieu-hendey/'
name = 'linkedin'

[[params.social]]
link = 'https://www.strava.com/athletes/15811815'
name = 'Strava'

[[params.social]]
link = 'https://www.last.fm/user/Mathieuhendey'
name = 'lastfm'

[[params.social]]
link = 'https://mathieuhendey.com/index.xml'
name = 'rss'

[[params.social]]
link = 'https://open.spotify.com/user/mathieuhendey?si=XfQnKgO5RJKGsXHey5YjQw'
name = 'spotify'

[[menu.main]]
name = 'home'
url = '/'
weight = 1

[[menu.main]]
name = 'posts'
url = '/posts'
weight = 2

[[menu.main]]
name = 'tags'
url = '/tags'
weight = 3

[[menu.main]]
name = 'categories'
url = '/categories'
weight = 4

[[deployment.targets]]
URL = 's3://mathieuhendey.com?region=us-west-2'
name = 'mathieuhendey.com S3 bucket'
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.goldmark.extensions]
typographer = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'xcode'
tabWidth = 4
